apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-hello-go
spec:
  pipelineRef:
    name: pipeline-hello-go
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/bradahlh/hellofromgo.git
    - name: branch-name
      value: main