---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-deploy
spec:
  params:
    - name: contextDir
      description: the context dir within source
      default: .
    - name: destinationImage
      description: the fully qualified image name
      default: "$(outputs.resources.app-image.url)"
    - name: dockerFile
      description: the docker file to used for building the application
      default: Dockerfile
  resources:
    inputs:
      - name: repo
        type: git
    outputs:
      - name: app-image
        type: image
  steps:
    - name: build-image
      image: quay.io/buildah/stable
      workingDir: "/workspace/repo/$(inputs.params.contextDir)"
      command:
        - buildah
      args:
        - bud
        - --layers
        - -f
        - $(inputs.params.dockerFile)
        - -t
        - $(inputs.params.destinationImage)
        - .
      securityContext:
        privileged: true
        runAsUser: 0
        