apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/bradahlh/hellofromgo
    - name: revision
      value: 6a71578c52ff4308a3af83fa09c98ada2acf84ce
---
# apiVersion: tekton.dev/v1alpha1
# kind: PipelineResource
# metadata:
#   name: tekton-tutorial-greeter-image
# spec:
#   type: image
#   params:
#     - name: url
#       # use internal registry
#       value: example.com/rhdevelopers/tekton-tutorial-greeter
#       # if you are on OpenShift uncomment the line below
#       #value: "image-registry.openshift-image-registry.svc:5000/tektontutorial/greeter"