apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-code
spec:
  type: git
  params:
    - name: url
      value: https://github.com/bradahlh/hellofromgo
    - name: revision
      value: main # Branch to be used
# ---
# apiVersion: tekton.dev/v1alpha1
# kind: PipelineResource
# metadata:
#   name: app-image
# spec:
#   type: image
#   params:
#     - name: url
#       value: example.com/bradahlh/hellofromgo