apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-hello-go
spec:
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from
    - name: branch-name
      type: string
      description: The git branch to clone
  workspaces:
    - name: shared-data
      description: |
        This workspace receives the cloned git repo and is passed to next
        Pipeline Task, which in turn writes the readme to the output.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: cat-readme
      runAfter:
        - "fetch-repo"
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        steps:
          - image: zshusers/zsh:latest
            script: |
              #!/usr/bin/env zsh
              cat $(workspaces.source.path)/README.md